name: day4
version: 0.1.0.0
license: MIT
github: "Sornaensis/aoc25"
author: "Sornaensis"
maintainer: "Sornaensis"
extra-source-files:
  - problem.md
  - input.txt

executables:
  day4-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - "-with-rtsopts=-N16"
    dependencies:
      - base >= 4.7 && < 5
      - array >= 0.5.8
      - parallel
